version: '3.8'

services:
  db:
    image: postgres
    container_name: ofereca-aqui-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=oferaca_aqui_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: